<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VehiculoSeeder extends Seeder
{
    public function run(): void
    {
        $vehiculos = [
            [
                'placa' => 'M-607460',
                'anio' => 2020,
                'marca' => 'YAMAHA',
                'modelo' => 'YBR 125 ED',
                'capacidad' => '2.00ASS',
                'tipo' => 'CARRETERA',
                'clase' => 'MOTOCICLETA',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'ROJO/GRIS C/F MULTICOLOR',
                'n_chasis' => 'LBPKE1309L0130850',
                'n_motor' => 'JYM154FMI20115354',
                'n_vin' => 'N/N DE FABRICA',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'M-483032',
                'anio' => 2019,
                'marca' => 'YAMAHA',
                'modelo' => 'YBR 125 ED',
                'capacidad' => '2.00ASS',
                'tipo' => 'CARRETERA',
                'clase' => 'MOTOCICLETA',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'ROJO/GRIS C/F MULTICOLOR',
                'n_chasis' => 'LBPKE1301K0128072',
                'n_motor' => 'JYM154FMI19088802',
                'n_vin' => 'N/N DE FABRICA 2',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'M-485140',
                'anio' => 2017,
                'marca' => 'YAMAHA',
                'modelo' => 'YBR 125 ED',
                'capacidad' => '2.00ASS',
                'tipo' => 'CARRETERA',
                'clase' => 'MOTOCICLETA',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'ROJO/NEGRO C/F MULTICOLOR',
                'n_chasis' => 'LBPKE1303H0120271',
                'n_motor' => 'JYM154FMI17032892',
                'n_vin' => 'N/T DE FABRICA',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'P-997029',
                'anio' => 2022,
                'marca' => 'CHEVROLET',
                'modelo' => 'N400',
                'capacidad' => '0.75TON',
                'tipo' => 'DE CARGA',
                'clase' => 'PANEL',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'BLANCO',
                'n_chasis' => 'LZWCDAGA5NC802696',
                'n_motor' => 'LMH1CM41910087',
                'n_vin' => 'LZWCDAGA5NC802696',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'P-4797B',
                'anio' => 2024,
                'marca' => 'TOYOTA',
                'modelo' => 'LITE ACE',
                'capacidad' => '0.80TON',
                'tipo' => 'DE CARGA',
                'clase' => 'PANEL',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'BLANCO C/DIST COMERCIAL',
                'n_chasis' => 'MHKB3FE100K002267',
                'n_motor' => '2NR4A55375',
                'n_vin' => 'N/T DE FABRICA 2',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'M-967492',
                'anio' => 2025,
                'marca' => 'YAMAHA',
                'modelo' => 'YBR 125 ED',
                'capacidad' => '2.00ASS',
                'tipo' => 'CARRETERA',
                'clase' => 'MOTOCICLETA',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'AZUL/NEGRO C/F MULTICOLOR',
                'n_chasis' => 'LBPKE1305S0146669',
                'n_motor' => 'JYM154FMI24225167',
                'n_vin' => 'N/T DE FABRICA 3',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'M-133064',
                'anio' => 2014,
                'marca' => 'YAMAHA',
                'modelo' => 'YBR 125 ED',
                'capacidad' => '2.00ASS',
                'tipo' => 'CARRETERA',
                'clase' => 'MOTOCICLETA',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'ROJO/NEGRO C/F MULTICOLOR',
                'n_chasis' => 'LBPKE130XE0093259',
                'n_motor' => 'JYM154FMI21143247',
                'n_vin' => 'N/T 1',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'M-834309',
                'anio' => 2022,
                'marca' => 'YAMAHA',
                'modelo' => 'YBR 125 ED',
                'capacidad' => '2.00ASS',
                'tipo' => 'CARRETERA',
                'clase' => 'MOTOCICLETA',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'ROJO/GRIS C/F MULTICOLOR',
                'n_chasis' => 'LBPKE1307N0139498',
                'n_motor' => 'JYM154FMI22180909',
                'n_vin' => 'N/T DE FABRICA 4',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'M-966162',
                'anio' => 2025,
                'marca' => 'YAMAHA',
                'modelo' => 'YBR 125 ED',
                'capacidad' => '2.00ASS',
                'tipo' => 'CARRETERA',
                'clase' => 'MOTOCICLETA',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'AZUL/NEGRO C/F MULTICOLOR',
                'n_chasis' => 'LBPKE1303S0146671',
                'n_motor' => 'JYM154FMI24225163',
                'n_vin' => 'N/T DE FABRICA 5',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'M-485113',
                'anio' => 2015,
                'marca' => 'YAMAHA',
                'modelo' => 'YBR 125 ED',
                'capacidad' => '2.00ASS',
                'tipo' => 'CARRETERA',
                'clase' => 'MOTOCICLETA',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'ROJO/NEGRO C/F MULTICOLOR',
                'n_chasis' => 'LBPKE1302F0111898',
                'n_motor' => 'JYM154FMI15005420',
                'n_vin' => 'N/T DE FABRICA 6',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'M-753045',
                'anio' => 2022,
                'marca' => 'YAMAHA',
                'modelo' => 'YBR 125 ED',
                'capacidad' => '2.00ASS',
                'tipo' => 'CARRETERA',
                'clase' => 'MOTOCICLETA',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'ROJO/GRIS C/F MULTICOLOR',
                'n_chasis' => 'LBPKE130XN0139463',
                'n_motor' => 'JYM154FMI22180484',
                'n_vin' => 'N/T DE FABRICA 7',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'P-787072',
                'anio' => 2017,
                'marca' => 'CHEVROLET',
                'modelo' => 'N300',
                'capacidad' => '0.72TON',
                'tipo' => 'DE CARGA',
                'clase' => 'PANEL',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'BLANCO',
                'n_chasis' => 'LZWCCAGA6HE390851',
                'n_motor' => 'LAQUH50420123',
                'n_vin' => 'N/T DE FABRICA 8',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'P-812641',
                'anio' => 2018,
                'marca' => 'CHEVROLET',
                'modelo' => 'N300',
                'capacidad' => '0.72TON',
                'tipo' => 'DE CARGA',
                'clase' => 'PANEL',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'BLANCO',
                'n_chasis' => 'LZWCCAGA5JE600684',
                'n_motor' => 'LAQUHB1320816',
                'n_vin' => 'N/T DE FABRICA 9',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'P-17D3C',
                'anio' => 2022,
                'marca' => 'CHEVROLET',
                'modelo' => 'N400',
                'capacidad' => '0.75TON',
                'tipo' => 'DE CARGA',
                'clase' => 'PANEL',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'BLANCO',
                'n_chasis' => 'LZWCDAGA4NC825855',
                'n_motor' => 'LMH1CN11810119',
                'n_vin' => 'LZWCDAGA4NC825855',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'P-87DF7',
                'anio' => 2025,
                'marca' => 'TOYOTA',
                'modelo' => 'LITE ACE',
                'capacidad' => '0.80TON',
                'tipo' => 'DE CARGA',
                'clase' => 'PANEL',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'BLANCO C/DIST COMERCIAL',
                'n_chasis' => 'MHKB3FE100K005288',
                'n_motor' => '2NR4D61943',
                'n_vin' => 'N/T DE FABRICA 10',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'M-595277',
                'anio' => 2020,
                'marca' => 'YAMAHA',
                'modelo' => 'YBR 125 ED',
                'capacidad' => '2.00ASS',
                'tipo' => 'CARRETERA',
                'clase' => 'MOTOCICLETA',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'ROJO/NEGRO C/F MULTICOLOR',
                'n_chasis' => 'LBPKE1304L0130562',
                'n_motor' => 'JYM154FMI20113566',
                'n_vin' => 'N/T DE FABRICA 11',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'M-966030',
                'anio' => 2025,
                'marca' => 'YAMAHA',
                'modelo' => 'YBR 125 ED',
                'capacidad' => '2.00ASS',
                'tipo' => 'CARRETERA',
                'clase' => 'MOTOCICLETA',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'AZUL/NEGRO C/F MULTICOLOR',
                'n_chasis' => 'LBPKE1304S0146677',
                'n_motor' => 'JYM154FMI24225172',
                'n_vin' => 'N/T DE FABRICA 12',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'M-771500',
                'anio' => 2022,
                'marca' => 'YAMAHA',
                'modelo' => 'YBR 125 ED',
                'capacidad' => '2.00ASS',
                'tipo' => 'CARRETERA',
                'clase' => 'MOTOCICLETA',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'ROJO/GRIS C/F MULTICOLOR',
                'n_chasis' => 'LBPKE1306N0139511',
                'n_motor' => 'JYM154FMI22180739',
                'n_vin' => 'N/T DE FABRICA 13',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'M-771510',
                'anio' => 2022,
                'marca' => 'YAMAHA',
                'modelo' => 'YBR 125 ED',
                'capacidad' => '2.00ASS',
                'tipo' => 'CARRETERA',
                'clase' => 'MOTOCICLETA',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'ROJO/GRIS C/F MULTICOLOR',
                'n_chasis' => 'LBPKE1300N0140329',
                'n_motor' => 'JYM154FMI22185045',
                'n_vin' => 'N/T DE FABRICA 14',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'M-485041',
                'anio' => 2017,
                'marca' => 'YAMAHA',
                'modelo' => 'YBR 125 ED',
                'capacidad' => '2.00ASS',
                'tipo' => 'CARRETERA',
                'clase' => 'MOTOCICLETA',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'ROJO/NEGRO C/F MULTICOLOR',
                'n_chasis' => 'LBPKE1306H0119652',
                'n_motor' => 'JYM154FMI16026391',
                'n_vin' => 'N/T DE FABRICA 15',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'M-490516',
                'anio' => 2017,
                'marca' => 'YAMAHA',
                'modelo' => 'YBR 125 ED',
                'capacidad' => '2.00ASS',
                'tipo' => 'CARRETERA',
                'clase' => 'MOTOCICLETA',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'ROJO/NEGRO C/F MULTICOLOR',
                'n_chasis' => 'LBPKE1308H0120365',
                'n_motor' => 'JYM154FMI17032901',
                'n_vin' => 'N/T DE FABRICA 16',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'M-692682',
                'anio' => 2022,
                'marca' => 'YAMAHA',
                'modelo' => 'YBR 125 ED',
                'capacidad' => '2.00ASS',
                'tipo' => 'CARRETERA',
                'clase' => 'MOTOCICLETA',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'ROJO/GRIS C/F MULTICOLOR',
                'n_chasis' => 'LBPKE1302N0137528',
                'n_motor' => 'JYM154FMI21165143',
                'n_vin' => 'N/T DE FABRICA 17',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'P-87DFB',
                'anio' => 2025,
                'marca' => 'TOYOTA',
                'modelo' => 'LITE ACE',
                'capacidad' => '0.80TON',
                'tipo' => 'DE CARGA',
                'clase' => 'PANEL',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'BLANCO C/DIST COMERCIAL',
                'n_chasis' => 'MHKB3FE100K005286',
                'n_motor' => '2NR4D61617',
                'n_vin' => 'N/T DE FABRICA 18',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'P-59C2',
                'anio' => 2022,
                'marca' => 'CHEVROLET',
                'modelo' => 'N400',
                'capacidad' => '0.75TON',
                'tipo' => 'DE CARGA',
                'clase' => 'PANEL',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'BLANCO',
                'n_chasis' => 'LZWCDAGA2NC806835',
                'n_motor' => 'LMH1CM71410560',
                'n_vin' => 'LZWCDAGA2NC806835',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'P-244056',
                'anio' => 2013,
                'marca' => 'CHEVROLET',
                'modelo' => 'CMV',
                'capacidad' => '0.50TON',
                'tipo' => 'DE CARGA',
                'clase' => 'PANEL',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'BLANCO',
                'n_chasis' => 'KL16B0A52DC014203',
                'n_motor' => 'F8CB985704KC2',
                'n_vin' => 'N/T 2',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'P-479A5',
                'anio' => 2024,
                'marca' => 'TOYOTA',
                'modelo' => 'LITE ACE',
                'capacidad' => '0.80TON',
                'tipo' => 'DE CARGA',
                'clase' => 'PANEL',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'BLANCO C/DIST COMERCIAL',
                'n_chasis' => 'MHKB3FE100K002270',
                'n_motor' => '2NR4A54858',
                'n_vin' => 'N/T DE FABRICA 19',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'P-726576',
                'anio' => 2016,
                'marca' => 'CHEVROLET',
                'modelo' => 'SPARK GT',
                'capacidad' => '5.00ASS',
                'tipo' => 'COMPACTO',
                'clase' => 'AUTOMOVIL',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'BLANCO',
                'n_chasis' => 'MA6CG6AD6GT000011',
                'n_motor' => 'B12D1982028KC3',
                'n_vin' => 'MA6CG6AD6GT000011',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'M-966484',
                'anio' => 2025,
                'marca' => 'YAMAHA',
                'modelo' => 'YBR 125 ED',
                'capacidad' => '2.00ASS',
                'tipo' => 'CARRETERA',
                'clase' => 'MOTOCICLETA',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'AZUL/NEGRO C/F MULTICOLOR',
                'n_chasis' => 'LBPKE1300S0146675',
                'n_motor' => 'JYM154FMI24225173',
                'n_vin' => 'N/T DE FABRICA 20',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'M-933581',
                'anio' => 2025,
                'marca' => 'YAMAHA',
                'modelo' => 'YBR 125 ED',
                'capacidad' => '2.00ASS',
                'tipo' => 'CARRETERA',
                'clase' => 'MOTOCICLETA',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'ROJO/NEGRO C/F MULTICOLOR',
                'n_chasis' => 'LBPKE1307S0145927',
                'n_motor' => 'JYM154FMI24219008',
                'n_vin' => 'N/T DE FABRICA 21',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'M-692496',
                'anio' => 2022,
                'marca' => 'YAMAHA',
                'modelo' => 'YBR 125 ED',
                'capacidad' => '2.00ASS',
                'tipo' => 'CARRETERA',
                'clase' => 'MOTOCICLETA',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'ROJO/GRIS C/F MULTICOLOR',
                'n_chasis' => 'LBPKE1303N0137523',
                'n_motor' => 'JYM154FMI21165099',
                'n_vin' => 'N/T DE FABRICA 22',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'M-685253',
                'anio' => 2022,
                'marca' => 'YAMAHA',
                'modelo' => 'YBR 125 ED',
                'capacidad' => '2.00ASS',
                'tipo' => 'CARRETERA',
                'clase' => 'MOTOCICLETA',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'ROJO/GRIS C/F MULTICOLOR',
                'n_chasis' => 'LBPKE1308M0135782',
                'n_motor' => 'JYM154FMI21149911',
                'n_vin' => 'N/T DE FABRICA 23',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'P-679214',
                'anio' => 2015,
                'marca' => 'CHEVROLET',
                'modelo' => 'N300',
                'capacidad' => '0.72TON',
                'tipo' => 'DE CARGA',
                'clase' => 'PANEL',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'BLANCO',
                'n_chasis' => 'LZWCCAGA4F6067065',
                'n_motor' => 'LAOUF42320847',
                'n_vin' => 'N/T DE FABRICA 24',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'P-941314',
                'anio' => 2021,
                'marca' => 'CHEVROLET',
                'modelo' => 'N400',
                'capacidad' => '0.75TON',
                'tipo' => 'DE CARGA',
                'clase' => 'PANEL',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'BLANCO',
                'n_chasis' => 'LZWCDAGA4MC800078',
                'n_motor' => 'LMH1CL40710359',
                'n_vin' => 'LZWCDAGA4MC800078',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'P-119EA2',
                'anio' => 2026,
                'marca' => 'TOYOTA',
                'modelo' => 'LITE ACE',
                'capacidad' => '0.8TON',
                'tipo' => 'DE CARGA',
                'clase' => 'PANEL',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'BLANCO C/DIST COMERCIAL',
                'n_chasis' => 'MHKB3FE100K007467',
                'n_motor' => '2NR4F29774',
                'n_vin' => 'MHKB3FE100K007467',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'P-976508',
                'anio' => 2021,
                'marca' => 'TOYOTA',
                'modelo' => 'HIACE',
                'capacidad' => '1.50TON',
                'tipo' => 'DE CARGA',
                'clase' => 'PANEL',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'BLANCO',
                'n_chasis' => 'JTCHK02P000015161',
                'n_motor' => '5L6339854',
                'n_vin' => 'N/T DE FABRICA 25',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'P-901114',
                'anio' => 2019,
                'marca' => 'CHEVROLET',
                'modelo' => 'N300',
                'capacidad' => '1.10TON',
                'tipo' => 'FURGON',
                'clase' => 'CAMION LIVIANO',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'BLANCO',
                'n_chasis' => 'LZWCAAGA2KE409585',
                'n_motor' => 'L3CUK71430044',
                'n_vin' => 'LZWCAAGA2KE409585',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'P-17A79',
                'anio' => 2022,
                'marca' => 'CHEVROLET',
                'modelo' => 'N400',
                'capacidad' => '0.75TON',
                'tipo' => 'DE CARGA',
                'clase' => 'PANEL',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'BLANCO',
                'n_chasis' => 'LZWCDAGA5NC825847',
                'n_motor' => 'LMH1CN11810200',
                'n_vin' => 'LZWCDAGA5NC825847',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'M-490517',
                'anio' => 2017,
                'marca' => 'YAMAHA',
                'modelo' => 'YBR 125 ED',
                'capacidad' => '2.00ASS',
                'tipo' => 'CARRETERA',
                'clase' => 'MOTOCICLETA',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'ROJO/NEGRO C/F MULTICOLOR',
                'n_chasis' => 'LBPKE1307H0120373',
                'n_motor' => 'JYM154FMI17032895',
                'n_vin' => 'N/T DE FABRICA 26',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'M-466343',
                'anio' => 2017,
                'marca' => 'YAMAHA',
                'modelo' => 'YBR 125 ED',
                'capacidad' => '2.00ASS',
                'tipo' => 'CARRETERA',
                'clase' => 'MOTOCICLETA',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'ROJO/NEGRO C/F MULTICOLOR',
                'n_chasis' => 'LBPKE1308H0120382',
                'n_motor' => 'JYM154FMI17032920',
                'n_vin' => 'N/T DE FABRICA 27',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'M-575434',
                'anio' => 2020,
                'marca' => 'YAMAHA',
                'modelo' => 'YBR 125 ED',
                'capacidad' => '2.00ASS',
                'tipo' => 'CARRETERA',
                'clase' => 'MOTOCICLETA',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'ROJO/NEGRO C/F MULTICOLOR',
                'n_chasis' => 'LBPKE1303K0129594',
                'n_motor' => 'JYM154FMI19101159',
                'n_vin' => 'N/T DE FABRICA 28',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'P-11574C',
                'anio' => 2026,
                'marca' => 'TOYOTA',
                'modelo' => 'LITE ACE',
                'capacidad' => '0.8TON',
                'tipo' => 'DE CARGA',
                'clase' => 'PANEL',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'BLANCO C/DIST COMERCIAL',
                'n_chasis' => 'MHKB3FE100K007067',
                'n_motor' => '2NR4F01071',
                'n_vin' => 'MHKB3FE100K007067',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'M-119038',
                'anio' => 2014,
                'marca' => 'YAMAHA',
                'modelo' => 'YBR 125 ED',
                'capacidad' => '2.00ASS',
                'tipo' => 'CARRETERA',
                'clase' => 'MOTOCICLETA',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'NEGRO C/F MULTICOLOR',
                'n_chasis' => 'LBPKE1303E0093703',
                'n_motor' => 'JYM154FMI16012121',
                'n_vin' => 'N/T 3',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'M-24379',
                'anio' => 2012,
                'marca' => 'YAMAHA',
                'modelo' => 'YBR 125 ED',
                'capacidad' => '2.00ASS',
                'tipo' => 'CARRETERA',
                'clase' => 'MOTOCICLETA',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'ROJO C/F GRIS/NEGRA',
                'n_chasis' => 'LBPKE1300C0074300',
                'n_motor' => 'JYM154FMI11031023',
                'n_vin' => 'N/T 4',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'P-399829',
                'anio' => 2008,
                'marca' => 'CHEVROLET',
                'modelo' => 'CMV',
                'capacidad' => '0.50TON',
                'tipo' => 'DE CARGA',
                'clase' => 'PANEL',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'BLANCO C/DIST COMERCIAL',
                'n_chasis' => 'KL1BB05568C154253',
                'n_motor' => 'F8CB013082KB2',
                'n_vin' => 'N/T 5',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'P-577602',
                'anio' => 2007,
                'marca' => 'TOYOTA',
                'modelo' => 'HILUX',
                'capacidad' => '1.5OTON',
                'tipo' => 'CABINA SIMPLE',
                'clase' => 'PICK UP',
                'en_calidad' => 'PROPIEDAD',
                'color' => 'GRIS',
                'n_chasis' => 'MR0CS12G800036561',
                'n_motor' => '2KD7261800',
                'n_vin' => 'N/D',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($vehiculos as $vehiculo) {
            DB::table('vehiculos')->updateOrInsert(
                ['placa' => $vehiculo['placa']], // Busca si la placa ya existe
                $vehiculo                         // Si existe lo actualiza, si no, lo inserta
            );
        }
    }
}